### ISSUE TITLE
Story "Updated Date" displays as 1/1/1970 before the story is published

### ISSUE THREAD

**Issue by rjucf** [UCF/Today-Child-Theme#72]
**Describe the bug**

When creating a story and previewing it before publishing the story the updated date displays as 1/1/1970.

**Steps to Reproduce**

1. Create a story
2. Preview the story before publishing it.

**Expected Behavior**

The "Updated Date" should not display unless the publish date has been changed.

**Possible Fix**

Hide the "Updated Date" until the story is published.

**Your environment:**

 - Browser & Version [e.g. chrome 68, safari]
 - WordPress Version: [e.g. 4.9.8]
 - Theme Version: [e.g. 1.5.2]

**Additional context**

**Comment by cjg89** [comment]
Resolved in v1.0.2.
